### ISSUE TITLE
Rethink resources in the stack based on recent projects

### ISSUE THREAD

**Issue by tommyphilyaw** [epandco/unthink-cli#13]
After using this stack heavily in the last few months a couple of things keeping cropping up that I would like to talk through in regards to the `resources`

Things noticed:
- It's not always clear where to place template vs api routes
- Mixing template and api routes in a single resource worked for really simple projects
- For larger projects it was clear that template routes need to live in their own resource and API calls in their own. Specifically so we can prefix api calls with `/api/...` to not take up meaningful url names that would be better displayed to the end user for template routes.
- Not a clear pattern on resources yet. My end goal with `resources` vs traditional `controllers` was to make them the service layer and use decorators to do away with the boiler plate of wiring a controller to a service typically done to keep controllers lean and business logic entirely in services.
  - To fully realize this goal (if still applicable) other perspectives are needed and some thought into the interface of a resource is needed and what the response from a response is so that it's not coupled to HTTP requests/express.

Some avenues I would like to explore:
- Splitting up resources to have better focus with an end result of a TemplateResource with template specific decorators and an ApiResource with Api focused decorators.
  - This would also allows us to prefix all API Resources by default as `/api/` without an explicit step to do so. With anything we would want to allow overrides but it seems like a sensible default
- Rebranding resources to services so in the item above it would be TemplateService / ApiService.
  - In doing so I think hashing out and nailing down where business logic lives and patterns of reuse would be essential before committing to this being the `service` layer.

**Comment by lxndrdagreat** [comment]
I think separating concerns via different resource types could be valuable. While I don't personally think the "where to place template vs api routes" is unclear (because it doesn't actually matter _where_, leaving the choice up to the design of the developer), I can see how some might have issues with it. I am used to Python-based frameworks like Flask and Starlette, where the organizational design was very much up to the developer, allowing for simplicity where able and complexity when required.

From the "Zen of Python":

> Simple is better than complex.
> Complex is better than complicated.

Maybe we need to have a larger chat about the business logic and services vs resources. I am really unsure about how to best separate things out at this time. Here are my thoughts:

I agree that resources could/should contain business logic, but at what point is there too much going on in a single resource? I am especially concerned with the quantity and quality of code in a single resource file.

- from _Zen of Python_: "Sparse is better than dense"
- from _Pragmatic Programmer_: "Every piece of knowledge must have a single, unambiguous, authoritative representation within a system."
- also from _Pragmatic Programmer_: "Design components that are self-contained, independent, and have a single, well-defined purpose."

I dislike having to parse through a multi-thousand-line file filled with multiple classes and functions. "Readability counts." (_Zen of Python_).

Maybe there is an issue with how we are using one resource to deliver several endpoints? For example, we might have a resource doing the following:

- 2-3 template responses for different routes
- 5-6 `get`, `post`, etc., API methods

So maybe we need to think through how much scope a single resource is allowed to handle?


> This would also allows us to prefix all API Resources by default as /api/ without an explicit step to do so

I am not sure about doing the prefix automatically. I think it might hide too much from the developer. I also think that as-is, the stack easily allows for three use cases that I think are common: projects that are just pages, projects that are pages and API, and projects that are just API. I think the prefix is a hindrance for the last one; if a project is just an API, then the prefix is definitely unneeded.

> Rebranding resources

I am also very unsure about this, and don't want to rush a change like that. Maybe if we figure out my other issues above, then this will be more clear. Currently, I think "Resource" is an accurate descriptor for the purpose.

**Comment by tommyphilyaw** [comment]
Initially felt the same way about the template and api routes being in the same resource but a few things in practice has made it more awkward than useful (perhaps confusing wasn't the right word):

- Resources typically specify a basePath
- All routes are relative to that base path meaning that if you specify a base as `users` you can't have `/api/users`
- This lack of prefixing on the api routes in a single resource leads to naming collisions in the urls. You likely want `/users` to serve up the template but for an API `/users` also makes sense for the data so you have think around that problem.
- An api prefix is probably almost always what you want to avoid this, but there can be exceptions. I would much rather this be setup to do what we want majority of the time and have options to override it. 

Perhaps the `@resource` decorator can options to control a prefix for api routes. It knows the difference between templates and api routes and should be easily doable. It could default to `/api/` for api routes and be cleared if need be. I don't see a reason not to default.

My rationale for splitting them goes beyond the prefixing issue (which probably can be solved with that this split) and is as follows:

- I would like resources to have better focus and more of a single responsibility
- Api resources would be just that ONLY API code with a strict set of semantics around it and I think would keep code cleaner.
- Similar thing with a Template Resource it would only server up templates and be dealing with that. 
- When getting into the weeds of authentication and securing routes I also think it would be cleaner when injecting middleware just because the behavior of a template route and api route is very different in how it needs to respond to things.
- I haven't seen a lot of benefit from a single resource serving up both. You are right that a simple app that wants data via API would need two resources but its not a heavy lift to add both and cleanly separates responsibilities (my opinion I get that).

On the topic of services vs resources I think we need to clearly define what a service is. To me a service should contain the public API to interact with a given business concept or domain. So a `user` service would contain the public API to do all the various operations for users. 

In that vein a few things for specifically API Services (which is another reason I think we want to split them, but just thinking out loud) I would like to explore:
- How can we define them such that it satisfies first aspect of being the `public interface` of the given domain it's representing (e.g user service). 
- This may require some more decoupling that we currently have such that responses from the Api Service could be consumed by any other piece of code and not tied to anything HTTP.
- Then with the use of decorators can we simply map based on those conventions an HTTP API to it in a clean way? We are kind of there, but can we get there is the question. 

What I'm not wanting is the following:

```
// Resource code
@get()
async getUsers(): Promise<...> {
  return userService.getUsers();
}
```

In practice I see this a lot with controllers where controllers are really lean and are nothing more than boiler plate that wires the input of the controller to the input of the service. That boiler plate I would like to cleanly abstract away.

Your concerns about too much code in one file are 100% valid but I would also argue that nothing I'm suggesting here is promoting that. In the example above someone could bloat the `userService` in the exact same way trying to keep resources lean. There is no substitute for good programming practices. 

I think its worth a more in depth discussion to hammer out the vernacular and ensure there is a clear role. Resources could be that "domain" layer vs services but I do want to avoid what I see as redundancy in the example above. The goal I'm aiming for is that Api Resources specifically are reusable pieces and can be composed and not tied to the HTTP layer at all beyond decorators.

**Comment by lxndrdagreat** [comment]
I totally agree that `getUsers()` calling out to `userService.getUsers()` is bad, and that the resource (using the current name) can and should be responsible for that.

> I would like resources to have better focus and more of a single responsibility

I think that is the key to a lot of the entire discussion. Single responsibility takes care of my concerns about DRY as well as lean.

> All routes are relative to that base path meaning that if you specify a base as users you can't have /api/users

In my case, I would have a UserViews resource and a UserApi resource, with appropriate base path. My only reason for pointing that out in the first place was because I think people were too tied to having everything in a single resource, leading to the base path issue. There is nothing stopping developers from separating things out better in the current structure.

Can you remind me (and maybe provide history for here) the reasons we went with the class-based architecture?

In various Python stacks I've used, if a class was used it would be extremely single-purpose, providing functionality for only one route. E.G., `class Users` would handle `/users`, with a different function for `GET`, `POST`, etc.. Alternatively, frameworks like Flask and Starlette use a function per route, and you would handle `GET` and `POST` by checking the request method inside the function.

I am wondering if switching to a function-based architecture would eliminate some of our issues. So a source file might export functions for several routes/methods.

I also think we should perhaps rethink how the decorators are used. I like how Python frameworks will use the decorator to determine route path information, but the return object is what determines the type (API vs Template or whatever else). Maybe the decorators are getting in our way; I'm not sure if the best way to get rid of them is via your idea for ApiResource and TemplateResource classes, or by better utilizing the return.

**Comment by tommyphilyaw** [comment]
@lxndrdagreat and I talked through this a bit and think we have a general direction to work toward. 

Highlights:

- Move away from decorators in favor of a light weight service / resource definition that decouples the class with the logic from the wiring up of the routes. 
- Keep the focus on trying to define this so that the API/Templates are more opinionated vs trying to be a general framework.

Some questions along the way:

- What is ServiceResult
- Can we genericize the “instance” class
- What all should exist on “context”
- Do we do “methods” and “handler” OR “no method” and “handlers” (because handlers would - define what methods)
- Are we covering our bases as far as all of the decorators is concerned
- How does “throw” work? They would need to be service oriented (loosely bound to “not found”, but not “HTTP” specific)

Specifically for

- Are we covering our bases as far as all of the decorators is concerned

The big thing I remembered after the chat was middleware. The decorators allow middleware to be wired up before the entire resource or on a per route level. This however is still 100% doable in this alternate form and already have some ideas around that.

I've created pr https://github.com/epandco/unthink-cli/pull/21 to track this.

**Comment by tommyphilyaw** [comment]
#35 closes this.
