### ISSUE TITLE
Run build scripts before running client/server

### ISSUE THREAD

**Issue by lukecjohnson** [epandco/unthink-cli#99]
Currently in a new `unthink-stack` project, the `client` and `server` npm scripts only execute `node ./scripts/dev.js` and `node ./lib/server/server.js` respectively. They do not first run any build scripts before starting.

This obviously means you can't immediately run `npm run server` in a fresh project, without first running `npm run build-server` which isn't a big deal, but it also means a frontend dev, for example, would have to always remember to run `npm run build-server` before running the server after pulling new changes.

Before separating the server/client scripts, the entire build script (including server, client, content, etc.) was run before starting up everything. Now, where should the boundary be with what should be built with `client` and `server`? Something like this?
```json
    "server": "npm run build-server && npm run build-content && node ./lib/server/server.js | pino-pretty --ignore req,res,responseTime,unthinkHandlerError,err --messageFormat=\"{msg} {unthinkHandlerError}\"",
    "client": "npm run build-client && npm run build-sass && npm run build-public && node ./scripts/dev.js"
```

**Comment by lxndrdagreat** [comment]
@matthewphilyaw I know you and I have chatted a bit about the `server` command, but I don't remember what we landed on. What are your thoughts on having the "run" commands also build their respective parts?

@lukecjohnson the `client` command definitely _would not_ run the `build-client` script or the `build-sass` script - there is no reason to "pre build" either of those because of how webpack and the sass watch task work (as run by `dev.js`). So in this case, it would just build the public folder and then run the dev script.

**Comment by lukecjohnson** [comment]
@lxndrdagreat Oh yeah, that makes sense for the client. Looks like there's an `--initial` flag for the `onchange` package that we could use to do an initial build for `watch-content` and `watch-public`. That way those tasks would work similarly to `watch-entries` and `watch-sass`

**Comment by matthewphilyaw** [comment]
@lxndrdagreat from memory I think where we landed was this:

- `npm run server` would build and run the server side components (assume that includes templates)
- `npm run client` runs everything related to the riot setup/watches etc
- `npm run build` we had started talking about repurposing this to do be the actual production build of the project spitting out the lib / dist / public folders etc.
